spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ekklesia_admin
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  cors:
    allowed-origins:
      - http://localhost:54898
      - http://localhost:50898
      - http://localhost:4200
      - http://localhost:3000
  bootstrap:
    admin:
      email: admin@ekklesia.com
      password: 123456
      name: Administrador
      tax-id: 12345678901
    church:
      name: Assembleia de Deus Missao Subsede Jardim Todos os Santos
      cnpj: 57166972000178
      city: Senador Canedo
      state: GO

jwt:
  secret: "k9G2+fR8Xy7p3vQq4W8sT2bN1yV6cR0dH5LqP4jK8sM="        # deve ter >=32 caracteres
  expirationMs: 3600000
